### ISSUE TITLE
Upload files to MedBook

### ISSUE THREAD

**Issue by rcurrie** [UCSC-Treehouse/operations#8]
@cameron please upload to medbook the expression levels from the following samples (located on pipeline0/outputs) if they have not already been uploaded:

-rwxrwx--- 1 adurbin pawg 116302405 Oct  5 08:46 TH01_0051_S01_RNASeq.tar.gz
-rwxrwx--- 1 adurbin pawg  87638106 Sep 27 10:20 TH01_0052_S01_RNASeq.tar.gz
-rwxrwx--- 1 adurbin pawg 113762791 Sep 27 10:20 TH01_0053_S01_RNASeq.tar.gz
-rwxrwx--- 1 adurbin pawg 111583344 Sep 27 10:21 TH01_0054_S01_RNASeq.tar.gz
-rwxrwx--- 1 adurbin pawg 109726028 Sep 27 11:08 TH01_0055_S01_RNASeq.tar.gz
-rwxrwx--- 1 adurbin pawg  98331356 Sep 29 16:19 TH01_0057_RNASeq.tar.gz
-rw-r--r-- 1 rcurrie pawg  95232656 Oct  5 08:46 TH01_0060_S01_RNASeq.tar.gz
-rwxrwx--- 1 adurbin pawg 113373221 Oct  5 08:46 TH01_0061_S01_RNASeq.tar.gz
-rwxrwx--- 1 adurbin pawg 111569757 Oct  5 08:46 TH01_0062_RNASeq.tar.gz
-rwxrwx--- 1 adurbin pawg 119073849 Oct  5 08:46 TH01_0063_RNASeq.tar.gz
-rwxrwx--- 1 adurbin pawg 102754563 Oct  5 08:46 TH01_0064_RNASeq.tar.gz
-rw-r--r-- 1 rcurrie pawg  88855918 Oct  5 08:46 TH01_0065_S01_RNASeq.tar.gz
-rw-r--r-- 1 rcurrie pawg  98532113 Oct  5 08:46 TH01_0069_S01_RNASeq.tar.gz
-rw-r--r-- 1 rcurrie pawg  88540071 Oct  5 08:46 TH01_0072_S01_RNASeq.tar.gz
-rw-r--r-- 1 rcurrie pawg  94965272 Oct  5 08:47 TH05_0109_S01_RNASeq.tar.gz
-rw-r--r-- 1 rcurrie pawg  93148919 Oct  5 08:47 TH05_0110_S01_RNASeq.tar.gz
-rw-r--r-- 1 rcurrie pawg  91118428 Oct  5 08:47 TH05_0111_S01_RNASeq.tar.gz

**Comment by cygao** [comment]
All files have been successfully uploaded and written to medbook

**Comment by cameron** [comment]
YMMV asking @cameron for anything ;)

**Comment by rcurrie** [comment]
@cameron doh! Thanks!

**Comment by e-t-k** [comment]
Hi @cygao , 

I can't find the following samples in the "California Kids Cancer Comparison" data set. Did you upload them to a different data set ? Did they have an error?

-rwxrwx--- 1 adurbin pawg 116302405 Oct 5 08:46 TH01_0051_S01_RNASeq.tar.gz
-rwxrwx--- 1 adurbin pawg 111569757 Oct 5 08:46 TH01_0062_RNASeq.tar.gz
-rwxrwx--- 1 adurbin pawg 119073849 Oct 5 08:46 TH01_0063_RNASeq.tar.gz
-rw-r--r-- 1 rcurrie pawg 98532113 Oct 5 08:46 TH01_0069_S01_RNASeq.tar.gz

Also, I see that the study has the sample labels for 51 and 69 , but mismatching study labels for 62 and 63.

		"ckcc/TH01_0051_S01_RNASeq",
		"ckcc/TH01_0062_S01_RNASeq",
		"ckcc/TH01_0063_S01_RNASeq",
		"ckcc/TH01_0069_S01_RNASeq",

**Comment by e-t-k** [comment]
Since this is time sensitive so I'm going to do the following. Let me know any info you have on these samples - but please don't re-upload them yourself while I'm working with them.

- In the Study, remove TH01_0062_S01_RNASeq and replace with TH01_0062_RNASeq
- same for 0063

In the data set, upload 51, 62, 63, and 69 with the sample IDs found in archive/output.

**Comment by cygao** [comment]
I will adderess this issue once I get off class (5pm)

**Comment by e-t-k** [comment]
Renamed the two sample IDs mentioned above , and uploaded the 4 samples mentioned above.

**Comment by e-t-k** [comment]
@cygao What's the status of this?

I have now checked all the files listed in the issue (instead of just the 4 that were time-sensitive) and I notice that the following 3 samples are also not uploaded to the CKCC data set in medbook:

TH01_0057_RNASeq
TH01_0064_RNASeq
TH01_0072_S01_RNASeq

it turns out that these should, in fact, be excluded from the CKCC data set, so it's convenient that they are not there; but I'd like to know what happened in case there is a bug with medbook.

**Comment by cygao** [comment]
@e-t-k On my end, it seems that I have (at least attempted to) upload these samples to Medbook in the past. Perhaps they were deleted after upload?

**Comment by e-t-k** [comment]
@cygao Can you look through your wrangler history, find the submission that lists these samples, &  send me the URL? Thanks.

**Comment by cygao** [comment]
57: 
>https://medbook.io/wrangler/editSubmission/hmwYRwBuSCjnXcY2e
Error due to uploaded file named differently (no s01) than CKCC study's defined name

64
>https://medbook.io/wrangler/editSubmission/EzMkffHgBmbiuYWPE
Same differences in file names as above 


72
>https://medbook.io/wrangler/editSubmission/EzMkffHgBmbiuYWPE
Seems to have uploaded fine

**Comment by e-t-k** [comment]
@cygao Thank you Cameron. I've tracked these down. Closing the ticket as all submissions are now accounted for (these 3 tracked down; I didn't track down the 4 I reuploaded since it is not worth the effort now that they are definitely present.)

Based on what we've learned, there's two things you need to do differently.

1. When you import a sample using any name that is different from the exact name listed in the log (even a tiny difference like 0057_S01_RNA vs 0057_RNA) , **document it in the ticket** so that we know to look under the different name. I was looking for TH01_0064_RNASeq
when TH01_0064_S01_RNASeq was already there.

2. **Check the wrangler submissions for an error message** when you think they are done, and ask us about it if you see one. You ran 13 samples in EzMkffHgBmbiuYWPE , but at least 1 of them did not get completed; the error message at the bottom of that page warns that something has gone wrong.

Excessive Details:
* TH01_0057_RNASeq  **Present in medbook under another name, not in use**
wrangler submission hmwYRwBuSCjnXcY2e abandoned due to sample name mismatch. 
renamed sample to TH01_0057_S01_RNASeq, wrangler submission EzMkffHgBmbiuYWPE.
This submission resulted in _Error running job: Internal error writing files to database_ but did successfully write 
TH01_0057_S01_RNASeq. However, we've retroactively decided to not use this sample in the compendium

* TH01_0064_RNASeq  **Present in medbook under another name, in use**
As 57, re-uploaded in submission EzMkffHgBmbiuYWPE as TH01_0064_S01_RNASeq , succesfully written.

* TH01_0072_S01_RNASeq - ** not present in medbook **
Claims to have been successfully written in job xkWwuTP2LFvcsRMAB  from same submission EzMkffHgBmbiuYWPE. However,  this job completed AFTER the associated FinishWranglerSubmission job, which means that it was /not/ written to the dataset.
